import type { Issuer } from "@/lib/pipeline";

/**
 * Where this site sends people, and which of those links pay us.
 *
 * Three rules, fixed before any link existed, and the reason they are in this
 * file rather than in somebody's head:
 *
 *   1. Every ranking and every rating is computed before a link is attached.
 *      Nothing in lib/rating.ts, lib/pipeline.ts or lib/sections.ts imports
 *      this file, and nothing here can change a score. A referral cannot move
 *      a token up the board because the board is finished by the time this
 *      runs.
 *   2. The referral is disclosed on the page that carries it, in words, not in
 *      a footer nobody reads.
 *   3. A referral sits only on an action button. Never on a venue's name
 *      inside a ranked row, never on an issuer's name in a table, never on a
 *      logo. If it is part of the data, it is not a link we are paid for.
 *
 * What actually pays, read from each company's own documentation on 7 Oct 2026:
 *
 *   Backpack  10% of the trading fees generated by a referred user who
 *             completes KYC, paid weekly, claimable for 24 months.
 *             Equity perps are explicitly excluded, so the rebate comes from
 *             people buying the tokenized stocks themselves.
 *             support.backpack.exchange/exchange/programs/referrals
 *   Hyperliquid 10% of a referred user's fees, and they get 4% off their first
 *             $25M of volume. Creating a code needs $10,000 of our own volume
 *             first, which we do not have, so the link here is plain.
 *             hyperliquid.gitbook.io/hyperliquid-docs/referrals
 *
 * What pays nothing, checked and recorded so nobody looks again: DexScreener,
 * Raydium, Orca, Meteora and PancakeSwap have no affiliate scheme to attach,
 * and no referral programme could be found on Phoenix's own documentation.
 * Jupiter pays only through an API integration, never through a link.
 */

export interface ActionLink {
  label: string;
  url: string;
  /** True when we are paid if somebody signs up through it. Drives the
   *  disclosure, so it is never set by hand at a call site. */
  referral: boolean;
}

/** Live referral links, by destination. A destination with no entry gets a
 *  plain link, which is the default rather than the exception. */
const REFERRAL: Partial<Record<string, string>> = {
  Backpack: "https://backpack.exchange/join/l51hjfee",
};

/** Plain links, for destinations that pay nothing or where we do not qualify
 *  for the programme yet. */
const PLAIN: Partial<Record<string, string>> = {
  Hyperliquid: "https://app.hyperliquid.xyz/trade",
};

/**
 * The buy action for a tokenized stock, if its issuer runs a venue we can send
 * somebody to. Only Backpack does today: they issue the token and they run the
 * exchange it is bought on, so one link does both jobs.
 *
 * Deliberately not offered for the others. xStocks, Ondo, PreStocks and Tessera
 * issue tokens that are bought on a DEX rather than on a venue of their own, and
 * the pools are already linked below.
 */
export function issuerAction(issuer: Issuer): ActionLink | null {
  const ref = REFERRAL[issuer];
  if (!ref) return null;
  return { label: `Buy on ${issuer}`, url: ref, referral: true };
}

/** The perp venue action. Hyperliquid is plain until we clear their $10,000
 *  volume requirement and can create a code. */
export function perpAction(name: string, url: string): ActionLink {
  const ref = REFERRAL[name];
  return {
    label: `Trade the perp on ${name}`,
    url: ref ?? url ?? PLAIN[name] ?? url,
    referral: Boolean(ref),
  };
}

/** A pool action. No DEX on Solana has an affiliate scheme, so these are always
 *  plain, and saying so here stops anybody adding a tracking parameter that
 *  earns nothing and looks like it does. */
export function poolAction(dex: string, url: string): ActionLink {
  return { label: dex, url, referral: false };
}

/** The disclosure, shown wherever a referral link appears. Written out rather
 *  than abbreviated, because the whole argument for a rating nobody pays to be
 *  in collapses if the one place money changes hands is vague about it. */
export const DISCLOSURE =
  "One link on this page is a referral: buying on Backpack through it pays us a " +
  "share of the trading fee, at no cost to you. It is the only one, it is marked, " +
  "and it changes nothing about the rating. Every score on this site is computed " +
  "before any link is attached, from figures the site publishes, and no issuer " +
  "applies or pays to be rated.";

/** True when any of these links pays us, so a page can decide whether the
 *  disclosure belongs on it at all. */
export const anyPaid = (links: (ActionLink | null)[]) =>
  links.some((l) => l?.referral);
